[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "games"
version = "0.0.0"
description = "Game collection"
requires-python = ">=3.8"


[tool.setuptools.packages.find]
where = ["src"]
include = ["games*"]

[tool.ruff]
target-version = "py38"
select = ["E", "F", "B", "UP", "I"]

[tool.black]
line-length = 88
target-version = ['py38']

